version: "3"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=hanusovedni

  web:
    volumes:
      - .:/code:delegated
    ports:
      - 9191:9191
    environment:
      - DJANGO_ENV=dev
    command: ./manage.py runserver 0:8000
